# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48157c849b4d1c594eb0b926c21278c04ad91998eb4dc2b69d2f72a34383782e16449f274640c73f024a7074c6174f6583876d533b67e6297d912801e758df2b

test:
  secret_key_base: 0915a29fd635795e8c476262584e3919bfa81955125b38e1f0221d79fb154cd902b735bdb11a88d5140dd8245ef1631aca2e17936f1b77e0e00536e6f7312fb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
